[package]
name = "mimc-rs"
version = "0.0.2"
authors = ["arnaucube <root@arnaucube.com>"]
edition = "2018"
license = "GPL-3.0"
description = "MIMC7 hash implementation"
repository = "https://github.com/arnaucube/mimc-rs"
readme = "README.md"

[dependencies]
num = "0.2.0"
num-bigint = "0.2.2"
num-traits = "0.2.8"
tiny-keccak = "1.5"
rustc-hex = "1.0.0"
rayon = "1.3.0"
